version: '3'

services:
  mck3dprintfarm:
    image: alastairtech/mck3dprintfarm:latest
    # You can also use a specific version tag:
    # image: alastairtech/mck3dprintfarm:1.0.0
    command: >
      sh -c "
        echo 'Initializing database...' &&
        mkdir -p /app/prisma &&
        touch /app/prisma/dev.db &&
        npx prisma generate &&
        echo 'Running Prisma migrations...' &&
        npx prisma migrate deploy --preview-feature &&
        echo 'Migrations complete. Starting application...' &&
        npm start
      "
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      # Don't mount the entire prisma directory, just create data volume for persistence
      - mck3dprintfarm_data:/app/prisma
      # Avoid mounting certificates since we're skipping HTTPS in dev mode in Docker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Skip HTTPS for Docker deployment
      - NEXTAUTH_URL=http://localhost:3000
      # NextAuth secret for JWT encryption and session security
      - NEXTAUTH_SECRET=your-super-secret-random-string-here-please-change-this
      # Database connection - fixed path for Docker
      - DATABASE_URL=file:/app/prisma/dev.db
      # Default admin user credentials
      - DEFAULT_ADMIN_EMAIL=admin@example.com
      - DEFAULT_ADMIN_PASSWORD=Admin123!
      - DEFAULT_ADMIN_NAME=Administrator
      # Add other environment variables as needed
    networks:
      - printfarm_network

# Named volumes for data persistence
volumes:
  mck3dprintfarm_data:

# Define custom networks with specific subnet
networks:
  printfarm_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.201.0.0/24
          gateway: 192.201.0.1 