name: Build and Push Docker Image

on:
  # Only allow manual triggering
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: mck3dprintfarm

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract version from package.json
      - name: Extract version from package.json
        id: package-version
        run: |
          VERSION=$(grep '"version"' package.json | cut -d '"' -f 4)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version extracted: $VERSION"

      # Login to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get Docker username in correct format
      - name: Prepare Docker Hub username
        id: prep
        run: |
          DOCKER_USER="${{ secrets.DOCKERHUB_USERNAME }}"
          # Convert username to lowercase and remove special characters
          SANITIZED_USER=$(echo "$DOCKER_USER" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_.-')
          echo "sanitized_user=$SANITIZED_USER" >> $GITHUB_OUTPUT
          echo "Using Docker Hub username: $SANITIZED_USER"
          
          # Full image name
          FULL_IMAGE_NAME="$SANITIZED_USER/${{ env.IMAGE_NAME }}"
          echo "full_image_name=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "Full image name: $FULL_IMAGE_NAME"

      # Build and push multi-platform images
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.prep.outputs.full_image_name }}:latest
            ${{ steps.prep.outputs.full_image_name }}:${{ steps.package-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Enable detailed build output for debugging
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Final message about success
      - name: Display completion message
        run: |
          echo "Successfully built and pushed multi-architecture Docker images:"
          echo "AMD64: ${{ steps.prep.outputs.full_image_name }}:latest"
          echo "ARM64: ${{ steps.prep.outputs.full_image_name }}:latest"
          echo "AMD64: ${{ steps.prep.outputs.full_image_name }}:${{ steps.package-version.outputs.version }}"
          echo "ARM64: ${{ steps.prep.outputs.full_image_name }}:${{ steps.package-version.outputs.version }}"
          echo ""
          echo "Images can be pulled with: docker pull ${{ steps.prep.outputs.full_image_name }}:latest"

      # Update Docker Hub Description
      # - name: Update Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
      #     short-description: "McKinnon Secondary College 3D Print Farm management application" 