name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: mck3dprintfarm

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract version from package.json
      - name: Extract version from package.json
        id: package-version
        run: |
          VERSION=$(grep '"version"' package.json | cut -d '"' -f 4)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version extracted: $VERSION"

      # Check Docker Hub credentials before attempting login
      - name: Verify Docker Hub credentials
        id: verify-creds
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "::error::Docker Hub username is not set. Please add DOCKERHUB_USERNAME secret."
            exit 1
          fi
          
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "::error::Docker Hub token is not set. Please add DOCKERHUB_TOKEN secret."
            echo "::error::Make sure the token has 'Read, Write, Delete' permissions from Docker Hub."
            echo "::error::To create a token, go to https://hub.docker.com/settings/security"
            exit 1
          fi
          
          echo "Docker Hub credentials provided. Proceeding with login..."

      # Login to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image without tags first
      - name: Build Docker image (without push)
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: local-image:latest

      # Build Docker image
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: local-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Enable detailed build output for debugging
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          # Add more detailed output to debug build issues
          outputs: type=docker,dest=/tmp/docker-image.tar

      # Check if build succeeded
      - name: Check image
        run: |
          docker image ls
          if ! docker image inspect local-image:latest > /dev/null 2>&1; then
            echo "Docker image build failed!"
            exit 1
          fi
          echo "Docker image built successfully"

      # Tag and push the image
      - name: Tag and push images
        run: |
          # Check login status
          docker info
          
          # Use the locally built image and tag it
          DOCKER_USER="${{ secrets.DOCKERHUB_USERNAME }}"
          VERSION="${{ steps.package-version.outputs.version }}"
          
          # Check username
          if [ -z "$DOCKER_USER" ]; then
            echo "::error::Docker Hub username is not set. Please add DOCKERHUB_USERNAME secret."
            exit 1
          fi
          
          # Ensure Docker username is valid (lowercase, no special chars)
          DOCKER_USER=$(echo "$DOCKER_USER" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')
          
          echo "Using Docker Hub username: $DOCKER_USER"
          echo "Using version: $VERSION"
          echo "Full image name: $DOCKER_USER/${{ env.IMAGE_NAME }}"
          
          # Verify Docker Hub login
          echo "Verifying Docker Hub login..."
          if ! docker login --username "$DOCKER_USER" --password-stdin <<< "${{ secrets.DOCKERHUB_TOKEN }}" > /dev/null 2>&1; then
            echo "::error::Failed to login to Docker Hub. Please check your credentials."
            echo "::error::Make sure your token has 'Read, Write, Delete' permissions from Docker Hub."
            echo "::error::To create a new token, go to https://hub.docker.com/settings/security"
            exit 1
          fi
          
          # Create repository if it doesn't exist (this may fail if user doesn't have permission, but that's ok)
          echo "Checking if repository exists..."
          
          # Tag the local image with proper tags
          echo "Tagging Docker image..."
          docker tag local-image:latest "$DOCKER_USER/${{ env.IMAGE_NAME }}:latest"
          docker tag local-image:latest "$DOCKER_USER/${{ env.IMAGE_NAME }}:$VERSION"
          
          # Push the tagged images
          echo "Pushing Docker image to Docker Hub..."
          set -x # Enable command echo for debugging
          docker push "$DOCKER_USER/${{ env.IMAGE_NAME }}:latest"
          docker push "$DOCKER_USER/${{ env.IMAGE_NAME }}:$VERSION"
          set +x # Disable command echo
          
          echo "Successfully pushed images to Docker Hub"

      # Update Docker Hub Description
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: "McKinnon Secondary College 3D Print Farm management application" 